services:
  postgres-db:
    container_name: content_app_container
    image: postgres:17.7
    environment:
      POSTGRES_DB: content-app
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: springbootstudent
    ports:
      - "5432:5432"
    volumes:
      - content_app_container_data:/var/lib/postgresql/data
  pgadmin:
    container_name: content_app_session_pgadmin
    image: dpage/pgadmin4:9.11
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
        - content_app_pgadmin_data:/var/lib/pgadmin
volumes:
  content_app_container_data:
  content_app_pgadmin_data:
